exports.formatNameList = [
  "[Gen 8] Random Battle",
  "[Gen 8] OU",
  "[Gen 8] Ubers",
  "[Gen 8] UU",
  "[Gen 8] LC",
  "[Gen 8] Monotype",
  "[Gen 8] 1v1",
  "[Gen 8] Anything Goes",
  "[Gen 8] ZU",
  "[Gen 8] LC UU",
  "[Gen 8] CAP",
  "[Gen 8] CAP LC",
  "[Gen 8] Battle Stadium Singles",
  "[Gen 8] Random Doubles Battle",
  "[Gen 8] Doubles OU",
  "[Gen 8] Doubles Ubers",
  "[Gen 8] Doubles UU",
  "[Gen 8] Doubles LC",
  "[Gen 8] VGC 2022",
  "[Gen 8] VGC 2021",
  "[Gen 8] VGC 2020",
  "[Gen 8] 2v2 Doubles",
  "[Gen 8] Metronome Battle",
  "[Gen 8] National Dex",
  "[Gen 8] National Dex AG",
  "[Gen 8] Random Dex",
  "[Gen 8 BDSP] Random Battle",
  "[Gen 8 BDSP] OU",
  "[Gen 8 BDSP] Ubers",
  "[Gen 8 BDSP] UU",
  "[Gen 8 BDSP] RU",
  "[Gen 8 BDSP] NU",
  "[Gen 8 BDSP] LC",
  "[Gen 8 BDSP] Monotype",
  "[Gen 8 BDSP] 3v3 Singles",
  "[Gen 8 BDSP] Doubles OU",
  "[Gen 8 BDSP] Battle Festival Doubles",
  "[Gen 8 BDSP] Pure Hackmons",
  "[Gen 8] The Loser's Game",
  "[Gen 8] Monotype Random Battle",
  "[Gen 8] Random Battle (No Dmax)",
  "[Gen 8] Random Battle Mayhem",
  "[Gen 8] BSS Factory",
  "[Gen 8] Super Staff Bros 4",
  "[Gen 8] Challenge Cup 1v1",
  "[Gen 8] Challenge Cup 2v2",
  "[Gen 7] Random Battle",
  "[Gen 7] Random Doubles Battle",
  "[Gen 7] Battle Factory",
  "[Gen 7] BSS Factory",
  "[Gen 7] Hackmons Cup",
  "[Gen 7 Let's Go] Random Battle",
  "[Gen 6] Random Battle",
  "[Gen 6] Battle Factory",
  "[Gen 5] Random Battle",
  "[Gen 4] Random Battle",
  "[Gen 3] Random Battle",
  "[Gen 2] Random Battle",
  "[Gen 1] Random Battle",
  "[Gen 7] OU",
  "[Gen 6] OU",
  "[Gen 5] OU",
  "[Gen 4] OU",
  "[Gen 3] OU",
  "[Gen 2] OU",
  "[Gen 1] OU",
  "[Gen 7] Ubers",
  "[Gen 7] UU",
  "[Gen 7] LC",
  "[Gen 7] Monotype",
  "[Gen 7] 1v1",
  "[Gen 7] Anything Goes",
  "[Gen 7] Battle Spot Singles",
  "[Gen 7 Let's Go] OU",
  "[Gen 7] Doubles OU",
  "[Gen 7] VGC 2019",
  "[Gen 7] VGC 2018",
  "[Gen 7] VGC 2017",
  "[Gen 7] Battle Spot Doubles",
  "[Gen 6] 1v1",
  "[Gen 6] Battle Spot Singles",
  "[Gen 6] Doubles OU",
  "[Gen 6] VGC 2016",
  "[Gen 6] VGC 2015",
  "[Gen 6] VGC 2014",
  "[Gen 6] Battle Spot Doubles",
  "[Gen 6] Battle Spot Triples",
  "[Gen 5] 1v1",
  "[Gen 5] GBU Singles",
  "[Gen 5] Doubles OU",
  "[Gen 5] VGC 2013",
  "[Gen 5] VGC 2012",
  "[Gen 5] VGC 2011",
  "[Gen 4] 1v1",
  "[Gen 4] Anything Goes",
  "[Gen 4] Doubles OU",
  "[Gen 4] VGC 2010",
  "[Gen 4] VGC 2009",
  "[Gen 3] Doubles OU",
  "[Gen 3] 1v1"
]
