exports.formatNameList = [
  "[Gen 8] Random Battle",
  "[Gen 8] OU",
  "[Gen 7] OU",
  "[Gen 8 BDSP] OU",
  "[Gen 8] LC",
  "[Gen 8] Monotype",
  "[Gen 8] 1v1",
  "[Gen 7] 1v1",
  "[Gen 6] 1v1",
  "[Gen 5] 1v1",
  "[Gen 4] 1v1",
  "[Gen 3] 1v1",
  "[Gen 8] Anything Goes",
  "[Gen 7] Anything Goes",
  "[Gen 8] Battle Stadium Singles",
  "[Gen 8] Battle Stadium Singles Series 9",
  "[Gen 8] VGC 2022",
  "[Gen 8] VGC 2021",
  "[Gen 7] Battle Spot Singles",
  "[Gen 7] Battle Spot Doubles",
  "[Gen 6] Battle Spot Singles",
  "[Gen 6] Battle Spot Triples",
  "[Gen 5] GBU Singles",
  "[Gen 8] Random Doubles Battle",
  "[Gen 8] Doubles OU",
  "[Gen 7] Doubles OU",
  "[Gen 8] 2v2 Doubles",
  "[Gen 8] Metronome Battle",
  "[Gen 8] National Dex",
  "[Gen 8] National Dex AG",
  "[Gen 8 BDSP] Random Battle",
  "[Gen 8 BDSP] 3v3 Singles",
  "[Gen 8] Monotype Random Battle",
  "[Gen 8] Random Battle Mayhem",
  "[Gen 8] BSS Factory",
  "[Gen 8] Super Staff Bros 4",
  "[Gen 8] Challenge Cup 1v1",
  "[Gen 8] Challenge Cup 2v2",
  "[Gen 7] Random Battle",
  "[Gen 7] Random Doubles Battle",
  "[Gen 7] Battle Factory",
  "[Gen 7] BSS Factory",
  "[Gen 7 Let's Go] Random Battle",
  "[Gen 6] Random Battle",
  "[Gen 6] Battle Factory",
  "[Gen 5] Random Battle",
  "[Gen 4] Random Battle",
  "[Gen 3] Random Battle",
  "[Gen 2] Random Battle",
  "[Gen 1] Random Battle"
];
