"use strict";

export const formatNameList: string[] = [
    "[Gen 8] Random Battle",
    "[Gen 8] OU",
    "[Gen 8] LC",
    "[Gen 8] Monotype",
    "[Gen 8] Ubers",
    "[Gen 7] OU",
    "[Gen 8] 1v1",
    "[Gen 7] 1v1",
    "[Gen 8] Anything Goes",
    "[Gen 8] Battle Stadium Singles",
    "[Gen 8] VGC 2022",
    "[Gen 8] VGC 2021",
    "[Gen 7] Battle Spot Singles",
    "[Gen 6] Battle Spot Triples",
    "[Gen 8] Random Doubles Battle",
    "[Gen 8] Metronome Battle",
    "[Gen 8] National Dex",
    "[Gen 8] National Dex AG",
    "[Gen 8 BDSP] Random Battle",
    "[Gen 8] Random Battle Mayhem",
    "[Gen 7] Random Battle",
    "[Gen 7 Let's Go] Random Battle",
];
