# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    Build:
        strategy:
            matrix:
                platform: [ubuntu-latest, windows-latest]
                node-version: [18.x]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Restore config.ts
              run: cp config/config-example.ts config/config.ts

            - name: Run prettier formatting
              run: npm run check

            - name: Run ESLint
              run: npm run lint

            - name: Check type definitions
              run: npm run tsc

            - name: Compile build.ts
              run: npm run pre-build

            - name: Test esbuild
              run: npm run esbuild
